version: "3"
services:
  windows:
    image: dockur/windows
    container_name: windows11
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    stop_grace_period: 2m
    environment:
      VERSION: "win11"
      RAM_SIZE: "4G"       # Adjust based on your Codespace machine type
      CPU_CORES: "2"       # Adjust based on your Codespace machine type
      DISK_SIZE: "64G"
    volumes:
      - ./win_data:/storage # Persists data to a folder in your repo
